2024-03-21 15:29:49,598 INFO    MainThread:8264 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-21 15:29:49,598 INFO    MainThread:8264 [wandb_setup.py:_flush():76] Configure stats pid to 8264
2024-03-21 15:29:49,600 INFO    MainThread:8264 [wandb_setup.py:_flush():76] Loading settings from C:\Users\games\.config\wandb\settings
2024-03-21 15:29:49,600 INFO    MainThread:8264 [wandb_setup.py:_flush():76] Loading settings from D:\programowanie\python\projekt zespo這wy\struktura\architectures\ml\RandomForest\wandb\settings
2024-03-21 15:29:49,600 INFO    MainThread:8264 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-21 15:29:49,600 INFO    MainThread:8264 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-21 15:29:49,600 INFO    MainThread:8264 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_RandomForest.py', 'program_abspath': 'D:\\programowanie\\python\\projekt zespo這wy\\struktura\\architectures\\ml\\RandomForest\\train_RandomForest.py', 'program': 'D:\\programowanie\\python\\projekt zespo這wy\\struktura\\architectures\\ml\\RandomForest\\train_RandomForest.py'}
2024-03-21 15:29:49,600 INFO    MainThread:8264 [wandb_init.py:_log_setup():526] Logging user logs to D:\programowanie\python\projekt zespo這wy\struktura\architectures\ml\RandomForest\wandb\run-20240321_152949-a8qpj23a\logs\debug.log
2024-03-21 15:29:49,601 INFO    MainThread:8264 [wandb_init.py:_log_setup():527] Logging internal logs to D:\programowanie\python\projekt zespo這wy\struktura\architectures\ml\RandomForest\wandb\run-20240321_152949-a8qpj23a\logs\debug-internal.log
2024-03-21 15:29:49,601 INFO    MainThread:8264 [wandb_init.py:init():566] calling init triggers
2024-03-21 15:29:49,601 INFO    MainThread:8264 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-21 15:29:49,601 INFO    MainThread:8264 [wandb_init.py:init():616] starting backend
2024-03-21 15:29:49,601 INFO    MainThread:8264 [wandb_init.py:init():620] setting up manager
2024-03-21 15:29:49,607 INFO    MainThread:8264 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-21 15:29:49,609 INFO    MainThread:8264 [wandb_init.py:init():628] backend started and connected
2024-03-21 15:29:49,623 INFO    MainThread:8264 [wandb_init.py:init():720] updated telemetry
2024-03-21 15:29:49,627 INFO    MainThread:8264 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-21 15:29:50,380 ERROR   MainThread:8264 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-21 15:29:50,876 ERROR   MainThread:8264 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "D:\programowanie\python\projekt zespo這wy\struktura\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "D:\programowanie\python\projekt zespo這wy\struktura\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-21 15:29:51,885 WARNING MsgRouterThr:8264 [router.py:message_loop():77] message_loop has been closed
