Traceback (most recent call last):
  File "D:\programowanie\python\projekt zespo≈Çowy\oko_neptuna\architectures\ml\RandomForest\train.py", line 65, in train
    clf(**config)
TypeError: 'RandomForestClassifier' object is not callable